{{- if .Values.nomad.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-proxy
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.nomad.proxy.service.type }}
  ports:
    - port: {{ .Values.nomad.proxy.service.port }}
      # targetPort: http
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "nomad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
{{- end}}