{{- if .Values.nomad.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomad.fullname" . }}-app
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.nomad.app.service.type }}
  ports:
    - port: {{ .Values.nomad.app.service.port }}
      # targetPort: http
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "nomad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
{{- end }}
