apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: nomad-prod-develop
spec:
  containers:
  - name: pvc-inspector
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: nomad-prod-develop-north-hub-db-dir
