nomad:
  config:
    version:
      label: distro
      isBeta: false
      usesBetaData: false

    gui:
      debug: true

    dbname: nomad_prod_v1_distro

    uploadurl: "https://cloud.nomad-lab.eu/prod/v1/distro/api/uploads"

    volumes:
      prefixSize: 1
      public: /nomad/distro/fs/public
      staging: /nomad/distro/fs/staging
      north_home: /nomad/distro/fs/north/users
      tmp: /nomad/distro/fs/tmp
      nomad: /nomad

    mail:
      enabled: false

    datacite:
      enabled: false

    north:
      enabled: false

    oasis:
      is_oasis: true
      uses_central_user_management: true

  image:
    repository: gitlab-registry.mpcdf.mpg.de/nomad-lab/nomad-distro
    tag: "latest"

  proxy:
    path: "/prod/v1/distro"

  app:
    replicaCount: 2

  worker:
    replicaCount: 1
    processes: 4
    resources:
      limits:
        memory: "32Gi"
      requests:
        memory: "8Gi"
