nomad:
  config:
    dbname: nomad_prod_v1

    uploadurl: "https://nomad-lab.eu/prod/v1/api/uploads"

    mail:
      enabled: true

    datacite:
      enabled: true

    north:
      enabled: true

    plugins:
      entry_points:
        options:
          'nomad_aitoolkit.apps:aitoolkit':
            upload_ids:
              - hHA2lM5HRy2ZN_La6TPGjg

  image:
    tag: "prod"

  proxy:
    path: "/prod/v1"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "25"
      nginx.ingress.kubernetes.io/denylist-source-range: "141.35.40.36/32, 141.35.40.52/32"

  app:
    replicaCount: 18

  worker:
    replicaCount: 1
    processes: 12
    resources:
      limits:
        memory: "32Gi"
      requests:
        memory: "8Gi"

jupyterhub:
  fullnameOverride: "nomad-prod-north"
  hub:
    baseUrl: "/prod/v1/north"
    config:
      GenericOAuthenticator:
        oauth_callback_url: https://nomad-lab.eu/prod/v1/north/hub/oauth_callback
  singleuser:
    podNameTemplate: "nomad-prod-north-{username}--{servername}"
