nomad:
  config:
    version:
      label: beta/staging
      isBeta: true
      usesBetaData: false
      officialUrl: "https://nomad-lab.eu/prod/v1/gui"

    gui:
      debug: true

    dbname: nomad_prod_v1

    uploadurl: "https://nomad-lab.eu/prod/v1/develop/api/uploads"

    mail:
      enabled: false

    datacite:
      enabled: false

    north:
      enabled: true

    plugins:
      entry_points:
        options:
          'nomad_aitoolkit.apps:aitoolkit':
            upload_ids:
              - hHA2lM5HRy2ZN_La6TPGjg

  image:
    tag: "prod"

  proxy:
    path: "/prod/v1/develop"

  app:
    replicaCount: 4

  worker:
    replicaCount: 1
    processes: 4
    resources:
      limits:
        memory: "32Gi"
      requests:
        memory: "8Gi"

jupyterhub:
  fullnameOverride: "nomad-prod-develop-north"
  hub:
    baseUrl: "/prod/v1/develop/north"
    config:
      GenericOAuthenticator:
        oauth_callback_url: https://nomad-lab.eu/prod/v1/develop/north/hub/oauth_callback
  singleuser:
    podNameTemplate: "nomad-prod-develop-north-{username}--{servername}"
