nomad:
  config:
    version:
      label: beta/staging
      isBeta: true
      usesBetaData: false
      officialUrl: "https://nomad-lab.eu/prod/v1/gui"

    gui:
      debug: true

    dbname: nomad_prod_v1

    uploadurl: "https://cloud.nomad-lab.eu/prod/v1/staging/api/uploads"

    mail:
      enabled: false

    datacite:
      enabled: false

    north:
      enabled: true

    plugins:
      entry_points:
        options:
          'nomad_aitoolkit.apps:aitoolkit':
            upload_ids:
              - hHA2lM5HRy2ZN_La6TPGjg

  image:
    tag: "prod"

  proxy:
    path: "/prod/v1/staging"

  app:
    replicaCount: 8

  worker:
    replicaCount: 2
    processes: 12
    resources:
      limits:
        memory: "32Gi"
      requests:
        memory: "8Gi"

jupyterhub:
  fullnameOverride: "nomad-prod-staging-north"
  hub:
    baseUrl: "/prod/v1/staging/north"
    config:
      GenericOAuthenticator:
        oauth_callback_url: https://nomad-lab.eu/prod/v1/staging/north/hub/oauth_callback
  singleuser:
    podNameTemplate: "nomad-prod-staging-north-{username}--{servername}"
