nomad:
  config:
    version:
      label: beta/staging
      isBeta: true
      usesBetaData: false
      officialUrl: "https://nomad-lab.eu/prod/v1/gui"

    gui:
      debug: true

    dbname: nomad_prod_v1

    uploadurl: "https://cloud.nomad-lab.eu/prod/v1/util/api/uploads"

    mail:
      enabled: false

    datacite:
      enabled: false

    north:
      enabled: false

    archive:
      use_new_writer: true

  image:
    tag: "prod"

  proxy:
    path: "/prod/v1/util"

  app:
    replicaCount: 1
    resources:
      limits:
        memory: "8Gi"

  worker:
    replicaCount: 2
    processes: 8
    resources:
      limits:
        memory: "256Gi"
      requests:
        memory: "8Gi"

  adminconsole:
    enabled: true
