{{- if .Values.nomad.ingress.enabled -}}
{{- $fullName := include "nomad.fullname" . -}}
{{- $svcPort := .Values.nomad.service.port -}}
{{- $path := .Values.nomad.proxy.path -}}
{{- if and .Values.nomad.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.nomad.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.nomad.ingress.annotations "kubernetes.io/ingress.class" .Values.nomad.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.nomad.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.nomad.proxy.timeout }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.nomad.proxy.connectionTimeout }}"
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.nomad.ingress.limitConnectionsApi }}"
    {{- with .Values.nomad.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.nomad.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.nomad.ingress.className }}
  {{- end }}
  {{- if .Values.nomad.ingress.tls }}
  tls:
    {{- range .Values.nomad.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.nomad.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ trimSuffix "/" $path }}/api
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-proxy
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-proxy
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
